DROP DATABASE IF EXISTS go;
CREATE DATABASE go;
DROP DATABASE IF EXISTS MSDS;
CREATE DATABASE MSDS;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Userdata;

DROP TABLE IF EXISTS MSDSCourseCatalog;


\c go;

CREATE TABLE Users (
    ID SERIAL,
    Username VARCHAR(100) PRIMARY KEY
);

CREATE TABLE Userdata (
    UserID Int NOT NULL,
    Name VARCHAR(100),
    Surname VARCHAR(100),
    Description VARCHAR(200)
);

\c msds

CREATE TABLE MSDSCourseCatalog (
    CID VARCHAR(100) PRIMARY KEY,
    CNAME VARCHAR(100),
    CPREREQ VARCHAR(100)
);
