---
title: "401_Study"
output: html_document
date: "2023-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General Stuff
``` {r loadstuff}

library(dplyr)
library(flux)
library(ggplot2)
library(gridExtra)
library(knitr)
library(rockchalk)
library(tidyverse)

```
## Visualizations

### Histograms

Base

```{r basehist}
can_unemp <- c(2.3, 2.8, 3.6, 2.4, 2.9, 3, 4.6, 4.4, 3.4, 4.6, 6.9, 6, 7,
               7.1, 5.9, 5.5, 4.7, 3.9, 3.6, 4.1, 4.8, 4.7, 5.9, 6.4, 6.3, 5.6,
               5.4, 7.1, 7.1, 8, 8.4, 7.5, 7.5, 7.6, 11, 12, 11.3, 10.6,
               9.7, 8.8, 7.8, 7.5, 8.1, 10.3, 11.2, 11.4, 10.4, 9.5, 9.6, 9.1,
               8.3, 7.6, 6.8, 7.2, 7.7, 7.6, 7.2, 6.8, 6.3, 6)

hist(x = can_unemp,
     breaks = c(1, 3, 5, 7, 9, 11, 13),
     main = "",  # suppress title
     xaxt = "n",  # suppress x-axis so we can specify exactly what we want
     xlab = "Unemployment Rates for Canada",
     xlim = c(0, 14),
     ylim = c(0, 20)  # y-axis range
     )
axis(side = 1, at = c(0, 14), labels=c("", ""), lwd.ticks = 0)
axis(side = 1, at = c(1, 3, 5, 7, 9, 11, 13))
```

```{r gghist}

ggplot(data = NULL, aes(x = can_unemp)) +
  geom_histogram(breaks = c(1, 3, 5, 7, 9, 11, 13)) +
  labs(x = "Unemployment Rates of Canada", y = "Frequency") +
  scale_x_continuous(breaks = c(1, 3, 5, 7, 9, 11, 13),
                   limits = c(0, 14))

```
### Frequency Polygons

```{r basefreq}

our_breaks <- c(1, 3, 5, 7, 9, 11, 13)  # or, seq(from = 1, to = 13, by = 2)
(our_grouped_data <- cut(x = can_unemp, breaks = our_breaks,
                         right = FALSE))  # 'right = FALSE' gives us x to < y

(freqs <- table(our_grouped_data))

(relative_freqs <- freqs / length(can_unemp))

(cumulative_freqs <- cumsum(freqs))

(class_midpoints <- seq(from = 2, to = 12, by = 2))

our_matrix <- cbind(freqs,
                    class_midpoints,
                    relative_freqs,
                    cumulative_freqs)

plot(x = class_midpoints,
     y = as.vector(freqs),  # recall that our "freqs" object is a table
     type = "l",  # to create a line plot
     xlab = "Class Midpoints",
     ylab = "Frequency")

```

```{r ggfreq}

ggplot(data = NULL, aes(x = class_midpoints, y = as.vector(freqs))) +
  geom_line() + labs(x = "Class Midpoints", y = "Frequency") +
  scale_x_continuous(breaks = class_midpoints)

```

### Cumulative Freq Poly

```{r basecumfreq}

plot(x = c(1, 3, 5, 7, 9, 11, 13),
     y = c(0, cumsum(freqs)),
     type = "b",  # b for "both" a point and line plot
     xaxt = "n",
     xlab = "Class Endpoints",
     xlim = c(0, 14),
     ylab = "Cumulative Frequency")
axis(side = 1, at = c(0, 14), labels=c("", ""), lwd.ticks = 0)
axis(side = 1, at = c(1, 3, 5, 7, 9, 11, 13))

```

```{r ggcumfreq}

ggplot(data = NULL, aes(x = c(1, 3, 5, 7, 9, 11, 13),
                        y = c(0, cumsum(freqs)))) +
  geom_line() +
  geom_point() +
  labs(x = "Class Midpoints", y = "Frequency") +
  scale_x_continuous(breaks = c(1, 3, 5, 7, 9, 11, 13))

```

### Dot plots

```{r basedot}

stripchart(x = can_unemp, method = "stack", pch = 20, at = 0,
           xlab = "Annual Unemployment Rates for Canada")

```

```{r ggdot}

ggplot(data = NULL, aes(x = can_unemp)) + geom_dotplot(binwidth = 0.2) +
  labs(x = "Annual Unemployment Rates for Canada") +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank()) +
  scale_x_continuous(breaks = c(1, 3, 5, 7, 9, 11, 13),
                     limits = c(1, 13))

```

### Stem

```{r basestem}

stem(can_unemp)

```

### Pies

```{r basepie}

petro_cap <- data.frame(company = c("Exxon Mobil", "Valero Energy", "Chevron",
                                    "ConocoPhilips", "Marathon Oil"),
                        capacity_1000 = c(5589, 2777, 2540, 2514, 1714))

pie(x = petro_cap$capacity_1000, labels = petro_cap$company)

```

```{r ggpie}

ggplot(data = petro_cap, aes(x = "", y = capacity_1000, fill = company)) +
  geom_bar(stat = "identity") +
  scale_fill_discrete(name = "Company") +  # just to capitalize our legend title
  coord_polar("y", start = 0) +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        axis.title = element_blank())

```

### Bars

```{r basebar}

barplot(height = petro_cap$capacity_1000,
        names.arg = petro_cap$company,
        ylab = "Capacity (in 1,000s barrels/day)",
        col = c("antiquewhite", "darksalmon", "darkseagreen", "cornflowerblue",
                "darkkhaki"))  # if we wanted color

```

```{r ggbar}

ggplot(data = petro_cap, aes(y = capacity_1000,
                             x = reorder(company, -capacity_1000),
                             fill = reorder(company, -capacity_1000))) +
         geom_bar(stat = "identity", col = "gray80") +
         labs(x = "", y = "Capacity (in 1,000s barrels/day)", fill = "Company") +
         scale_fill_discrete(type = c("antiquewhite", "darksalmon",
                                      "darkseagreen", "cornflowerblue",
                                      "darkkhaki")) 

```

### Paretos

```{r basepareto}

petro_cap$cum_prop <- cumsum(petro_cap$capacity_1000) /
  sum(petro_cap$capacity_1000)

pareto_chart <- barplot(height = petro_cap$capacity_1000,
        names.arg = petro_cap$company,
        ylab = "Capacity (in 1,000s barrels/day)",
        ylim = c(0, 1.05 * max(cumsum(petro_cap$capacity_1000)))
        )
lines(x = pareto_chart, y = cumsum(petro_cap$capacity_1000),
      type = "b", col = "deepskyblue4")

par(mar = c(5.1, 4.1, 4.1, 4.1))  # default is [1] 5.1 4.1 4.1 2.1
axis(side = 4, at = c(0, cumsum(petro_cap$capacity_1000)),
     labels = paste(c(0, round(petro_cap$cum_prop * 100)), "%", sep = ""),
     las = 1, col.axis = "deepskyblue4", col = "deepskyblue4")

```

```{r ggpareto}

ggplot(data = petro_cap, aes(y = capacity_1000,
                             x = reorder(company, -capacity_1000))) +
  geom_bar(stat = "identity") +
  geom_point(aes(y = cumsum(capacity_1000)), color = "deepskyblue4", pch = 16) +
  geom_path(aes(y = cumsum(capacity_1000), group = 1),
            color = "deepskyblue4", lty = 2) +
  labs(x = "Company", y = "Capacity (in 1,000s barrels/day)") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
