-- SQLite
SELECT 
    CUSTOMER.CUS_CODE as customer_code,
    CUSTOMER.CUS_LNAME AS customer_lname,
    INVOICE.INV_NUMBER AS invoice_number,
    LINE.LINE_UNITS AS line_units,
    PRODUCT.P_DESCRIPT AS product_description,
    LINE.LINE_PRICE AS line_price,
    LINE.LINE_PRICE * LINE.LINE_UNITS AS subtotal
FROM CUSTOMER
    LEFT JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
    LEFT JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
    LEFT JOIN PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE
WHERE invoice_number IS NOT NULL
ORDER BY customer_code,invoice_number,LINE.LINE_NUMBER



