### Business Statistics for Contemporary Decision Making (Black)
### Chapter 5, Discrete Distributions

library(ggplot2)
library(ggtext)

# "The overall learning objective of Chapter 5 is to help you understand a
# category of probability distributions that produces only discrete outcomes."

# A discrete random variable will have a limited or countably infinite set of 
# possible values. Black (p. 131) notes continuous random variables are
# generated by processes which 'are "measured" not "counted." ' If we record the
# time between customer arrivals to a shop, our possible values are limited only
# by the constraint of precision. It could be one minute between arrivals, one
# minute and one second, one minute and one millisecond less than one second,
# etc. 'Time between' is a measurement; a continuous one. If, instead, we count
# the number of customers arriving over a period of time, our values are
# necessarily limited to integers. One or two or n customers may arrive during
# a period of time, but we won't - unless we're delving into the macabre - have
# fractions of an arrival. "No. of customers" is a count; necessarily, discrete.

# 5.2 Describing a Discrete Distribution provides formulae for calculating the
# expected value (i.e. mean), variance and standard deviation of a discrete
# distribution. We'll use the Crises Data from Table 5.2 (p. 132).

# In R, we'll usually want to create two (2) vectors:  one (1) representing the
# outcomes possible in our 'universe' and one (1) with individual probabilities
# of those outcomes.

# From the Crises Data:
no_of_crises <- 0:5  # or c(0, 1, 2, 3, 4, 5)
prob_of_crises <- c(0.37, 0.31, 0.18, 0.09, 0.04, 0.01)

# Now, for the arithmetic mean - what most of us think of as the average or
# mean - we sum our values and divide by the number of values. Here, though,
# each of these values needs to be 'weighted' its probability. So, our expected
# value is the sum of the products of each outcome and its probability.

(expect_val <- sum(no_of_crises * prob_of_crises))  # [1] 1.15

# Variance and standard deviation are similarly calculated. We will square the
# difference between each outcome and the expected value - just as we would for
# continuous values - but multiple each squared difference by the relevant
# probability before summing across outcomes to get our variance.

sum((no_of_crises - expect_val)^2 * prob_of_crises)  # [1] 1.4075

# The standard deviation is the square root of the variance.
sqrt(sum((no_of_crises - expect_val)^2 * prob_of_crises))  # [1] 1.186381

# If we want, we can write our own function(s) using these formulae.

discrete_summary <- function(outcomes, probs) {
  expect_val <- sum(outcomes * probs)
  var <- sum((outcomes - expect_val)^2 * probs)
  return(list('Expected Value' = expect_val, 'Variance' = var,
              'Standard Deviation' = sqrt(var)))
}

# And, then:
discrete_summary(outcomes = no_of_crises, probs = prob_of_crises)


# 5.3 introduces the binomial distribution. The binomial distribution - similar
# to how a normal distribution is defined by a mean and standard deviation -
# is defined by an 'n' presenting the number of identical trials or events, and
# a  'p,' the probability of "success" for any one (1) trial or event. Note that
# each trial or event has only two (2) outcomes:  "success" or "failure."

# A step back:  R, for many distributions, has an existing set of functions for
# doing different things. These are:
# 'd' functions for returning a density estimate,
# 'p' functions for returning the probability to the left (less than or equal
# to) or to the right (greater than) of a given value or quantile.
# 'q' functions for returning the value or quantile for one (1) or more
# probabilities, and
# 'r' functions for returning random values generated from the specified
# distribution.

# For the binomial distribution, we have dbinom(), pbinom(), qbinom() and
# rbinom().

# Looking at Demonstration Problem 5.4 (p. 141)

# One study by CNNMoney reported that 60% of workers have less than $25,000 in
# total savings and investments (excluding the value of their home). If this is
# true and if a random sample of 20 workers is selected, what is the probability
# that fewer than 10 have less than $25,000 in total savings and investments?

# Because we're interested in 'less than 10' - the 'lower tail' - we will use
# pbinom().

# First, we'll define our n and p:
n <- 20
p <- 0.6

# Second, we'll use pbinom(), just like we'd use a binomial table, to return
# probability associated with seeing 9 or fewer workers w/ < $25,000.
pbinom(q = 9, size = n, prob = p, lower.tail = TRUE)  # [1] 0.1275212

# Note that, because this is a discrete distribution, we could alternatively
# sum the individual densities from 0 to 9.
sum(dbinom(x = 0:9, size = n, prob = p))  # [1] 0.1275212

# To calculate the mean and standard deviation of a binomial distribution, we'll
# implement the same formulae given on p. 142. We'll use the distribution
# specified on p. 142 to demonstrate and match the 'Excel Output' Table 5.8
n <- 20
p <- 0.14

(binom_mean <- n * p)  # [1] 2.8
(binom_sd <- sqrt(n * p * (1 - p)))  # [1] 1.551773

# And to match Table 5.8
options(scipen = 999)  # this is just to 'suppress' scientific notation
data.frame(x = 6:20, PROB_x = round(dbinom(6:20, 20, 0.14), 4))
options(scipen = 0)  # return to default

# We can similar recreate the figures on p. 143
ggplot(data = NULL, aes(x = 0:8, y = dbinom(x = 0:8, size = 8, prob = 0.2))) +
         geom_bar(stat = "identity") +
  ggtitle("Binomial distribution:  *n* = 8 and *p* = 0.20") +
  labs(x = "*x* Values", y = "Probability") +
  scale_x_continuous(breaks = 0:8, labels = 0:8) +
  theme(axis.title.x = ggtext::element_markdown(),
        plot.title = ggtext::element_markdown())

# Lastly, we'll work through Demonstration Problem 5.5 (p. 144)
# A manufacturing company produces 10,000 plastic mugs per week. This company
# supplies mugs to another company, which packages the mugs as part of picnic
# sets. The second company randomly samples 10 mugs sent from the supplier. If
# two or fewer of the sampled mugs are defective, the second company accepts
# the lot. What is the probability that the lot will be accepted if the mug
# manufacturing company actually is producing mugs that are 10% defective?
# 20% defective? 30% defective? 40% defective?
n <- 10
p <- c(0.1, 0.2, 0.3, 0.4)

data.frame(p = p,
           lot_accept_p = round(pbinom(q = 2, size = n, prob = p), 3),
           expected_defects = n * p)


# 5.4 introduces the Poisson distribution. A Poisson distribution 'describes
# discrete occurrences over a continuum or interval.' Any Poisson distribution
# is fully described by its 'lambda.' Lambda is the expected number of
# occurrences during the interval of interest; think long-running average.

# Demonstration Problem 5.6 (p. 149)
# Suppose that during the noon hour in the holiday season, a UPS store averages
# 2.3 customers every minute and that arrivals at such a store are Poisson
# distributed. During such a season and time, what is the probability that more
# than four customers will arrive in a given minute?
lambda <- 2.3

ppois(q = 4, lambda = lambda, lower.tail = FALSE)  # [1] 0.08375072

# Alternatively, just like we demonstrated with the binomial distribution, we
# can estimate probabilities as the sum of individual densities.

sum(dpois(x = 5:15, lambda = lambda)) < ppois(q = 4, lambda = lambda, lower.tail = FALSE)


# We can always dpois() to return the densities provided in Table 5.10 on p.
# 149.
options(scipen = 999) 
data.frame(x = 0:9, PROBABILITY = round(dpois(x = 0:9, lambda = 1.6), 4))
options(scipen = 0)

# The mean and variance of a Poisson distribution are its lambda. The standard
# deviation is equal to the square root of its lambda.

# Just as we did for our binomial example, we'll plot the probabilities in a
# barplot.

ggplot(data = NULL, aes(x = 0:9, y = dpois(x = 0:9, lambda = 1.6))) +
  geom_bar(stat = "identity") +
  ggtitle(expression("Poisson distribution for" ~ lambda ~ "= 1.6")) +
  labs(x = " ", y = "Probability") +
  scale_x_continuous(breaks = 0:9, labels = 0:9)


# 5.5 introduces the hypergeometric distribution. Like the binomial
# distribution, the 'events' of interest have two (2) outcomes:  'success' or
# 'failure.' However, each event is not independent because the population,
# N, is known, and the number of 'successes' in the population, A, is known, and
# when we sample from our distribution, we are (necessarily) sampling without
# replacement.

# For our example, we'll work Demonstration Problem 5.8.
# Suppose 18 major companies operate in the United States and 12 are located in
# California's Silicon Valley. If three computer companies are selected randomly
# from the entire list, what is the probability that one or more of selected
# companies are located in Silicon Valley.

m <- 12  # these are the 'successes' in our population; our 'A'
n <- 18 - m  # these are the 'failures,' N - A
k <- 3  # this is the number of draws | samples

# So, we are interested in the probability of drawing one or more Silicon Valley
# companies, of which there are 12, from our population of 18, across three (3)
# draws.
phyper(q = 0, m = m, n = 18 - m, k = 3, lower.tail = FALSE)  # [1] 0.9754902

# Note that we used q = 0 because, like the other distribution ("p") and
# quantile ("q") functions, when lower.tail = TRUE it returns the value or
# probability LESS THAN OR EQUAL to 'p' or 'q.' So, with q = 0, we get the
# probability of all outcomes above 0; here, 1, 2 or 3.

# Alternatively, we can use the choose() function to return the number of
# combinations and calculate the individual probabilities of x = 1, x = 2 and 
# x = 3, just like they did for the Demonstration Problem.

(x1 <- choose(n = 12, k = 1) * choose(6, 2) / choose(18, 3))  # [1] 0.2205882
(x2 <- choose(n = 12, k = 2) * choose(6, 1) / choose(18, 3))  # [1] 0.4852941
(x3 <- choose(n = 12, k = 3) * choose(6, 0) / choose(18, 3))  # [1] 0.2696078

# Then,
sum(x1, x2, x3)  # [1] 0.9754902

# Lastly, we could've used the law of complements, as Black does, understanding
# that the probability of at least one is equal to one (1) minus the probability
# of none.

# So, the probability of none of the companies drawn being from Silicon Valley?
choose(12, 0) * choose(6, 3) / choose(18, 3)  # [1] 0.0245098

# And,
1 - (choose(12, 0) * choose(6, 3) / choose(18, 3))  # [1] 0.9754902

# Next to last lastly,
# choose(), under the hood, is executing factorial(n) / (factorial(r) *
# factorial(n - r)) for calculating the number of combinations. Just to prove
# this for ourselves:
choose(18, 3)  # [1] 816

factorial(18) / (factorial(3) * factorial(18 - 3))  # [1] 816

# Actual lastly, we'll solve the probabilities presented in Table 5.13 and 5.14
# with the Minitab and Excel outputs.

# Where N = 24 people of whom A = 8 are women, n = 5 are randomly selected, and
# x = 3 are women. What is the probability of drawing three (3) women?

dhyper(x = 3, m = 8, n = 24 - 8, k = 5)  # [1] 0.1581028
